---
title: "Solucion Ejercicio"
author: "Anna Cabrerizo Requena"
date: "2023-10-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## EJERCICIO 

a)
```{r}
library(MASS)
library(robustbase)

?mammals
?Animals2
```

b)

```{r}
dim(mammals)  
head(mammals)  
tail(mammals)  
str(mammals)  
```

```{r}
dim(Animals2)  
head(Animals2)  
tail(Animals2)  
str(Animals2)  
```

c)

```{r}
rownames(mammals)
colnames(mammals)
```

```{r}
rownames(Animals2)
colnames(Animals2)
```

d)

```{r}
commonAnimals <- intersect(rownames(mammals), rownames(Animals2))
commonAnimals
```

e)

```{r}
animalsInMammals <- rownames(mammals)
animalsInAnimals2 <- rownames(Animals2)

# Animales que están en mammals pero no en Animals2
animalsOnlyInMammals <- setdiff(animalsInMammals, animalsInAnimals2)

# Animales que están en Animals2 pero no en mammals
animalsOnlyInAnimals2 <- setdiff(animalsInAnimals2, animalsInMammals)

# Número de animales en cada categoría
numAnimalsOnlyInMammals <- length(animalsOnlyInMammals)
numAnimalsOnlyInAnimals2 <- length(animalsOnlyInAnimals2)

cat("Animales en mammals pero no en Animals2:\n")
cat(animalsOnlyInMammals, sep = ', ')

cat("\n\nAnimales en Animals2 pero no en mammals:\n")
cat(animalsOnlyInAnimals2, sep = ', ')

cat("\n\nNúmero de animales en mammals pero no en Animals2:", numAnimalsOnlyInMammals)
cat("\nNúmero de animales en Animals2 pero no en mammals:", numAnimalsOnlyInAnimals2)

```


